# This workflow is a convenient way to run flaky tests.  Go down to the
# "Run tests" step to read about how to add tests to the TESTS array.

# The built-in `secrets.GITHUB_TOKEN` token is limited in what it can do so a personal
# access token is used in certain situations.  e.g. Accessing another repository or
# having a workflow trigger another workflow.

name: Test (QA Flaky)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install libgtk2.0-0
        run: |
          sudo apt-get update
          sudo apt-get install libgtk2.0-0

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 429280
        id: setup-chrome
      - run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version